services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:4.0-management
    restart: unless-stopped
    hostname: rabbitmq
    volumes:
      - "./docker-data/rabbitmq:/var/lib/rabbitmq"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
