version: "3.8"

services:
  loki:
    container_name: loki
    image: grafana/loki
    restart: unless-stopped
    ports:
      - 3100:3100
    volumes:
      - ./data/loki/:/etc/loki
    command: -config.file=/etc/loki/loki-config.yaml

  promtail:
    container_name: promtail
    image: grafana/promtail
    restart: unless-stopped
    volumes:
      - /var/log:/var/log:ro
      - ./data/webapi/:/webapi:ro
      - ./data/promtail:/etc/promtail
    command: -config.file=/etc/promtail/promtail-config.yaml

  grafana:
    container_name: grafana
    image: grafana/grafana
    restart: unless-stopped
    volumes:
      - ./data/grafana:/var/lib/grafana
    ports:
      - 3000:3000
